from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.login, name = 'login'),
    # path('dashboard', views.dashboard, name = 'dashboard'),
    path('shift_sub_admin', views.shift_sub_admin, name = 'shift_sub_admin'),
    path('login_check', views.login_check, name = 'login_check'),
    path('dashboard', views.dashboard, name = 'dashboard'),
    path('logout_view', views.logout_view, name = 'logout_view'),
    path('show_user', views.show_user, name = 'show_user'),
    path('show_user_data', views.show_user_data, name = 'show_user_data'),
    path('show_role', views.show_role, name = 'show_role'),
    path('delete_user', views.delete_user, name = 'delete_user'),
    path('get_user_ajax', views.get_user_ajax, name = 'get_user_ajax'),
    path('add_user', views.add_user, name = 'add_user'),
    path('edit_user', views.edit_user, name = 'edit_user'),
    path('show_role_data', views.show_role_data, name = 'show_role_data'),
    path('approve_disapprove_role', views.approve_disapprove_role, name = 'approve_disapprove_role'),
    path('add_role', views.add_role, name = 'add_role'),
    path('delete_role', views.delete_role, name = 'delete_role'),
    path('get_role_ajax', views.get_role_ajax, name = 'get_role_ajax'),
    path('edit_role', views.edit_role, name = 'edit_role'),
    path("home",views.home, name="home"),
    path("show_devicetype",views.show_devicetype, name="show_devicetype"),
    path("show_location",views.show_location, name="show_location"),
    path("show_device_type_data",views.show_device_type_data, name="show_device_type_data"),
    path("add_device_type",views.add_device_type, name="add_device_type"),
    path("get_device_type_ajax",views.get_device_type_ajax, name="get_device_type_ajax"),
    path("edit_device_type",views.edit_device_type, name="edit_device_type"),
    path("delete_device_type",views.delete_device_type, name="delete_device_type"),
    path("show_location_data",views.show_location_data, name="show_location_data"),
    path("add_Location",views.add_Location, name="add_Location"),
    path("get_location_ajax",views.get_location_ajax, name="get_location_ajax"),
    path("edit_location",views.edit_location, name="edit_location"),
    path("delete_location",views.delete_location, name="delete_location"),
    path("show_Department",views.show_Department, name="show_Department"),
    path("show_department_data",views.show_department_data, name="show_department_data"),
    path("add_department_data",views.add_department_data, name="add_department_data"),
    path("get_department_name_ajax",views.get_department_name_ajax, name="get_department_name_ajax"),
    path("edit_department_name",views.edit_department_name, name="edit_department_name"),
    path("delete_department_name",views.delete_department_name, name="delete_department_name"),
    path("show_employees",views.show_employees, name="show_employees"),
    path("show_employees_data",views.show_employees_data, name="show_employees_data"),
    path("delete_EmployeesData_type",views.delete_EmployeesData_type, name="delete_EmployeesData_type"),
    path("show_devices",views.show_devices, name="show_devices"),
    path("show_devices_data",views.show_devices_data, name="show_devices_data"),
    path("get_view_fun_devices_ajax",views.get_view_fun_devices_ajax, name="get_view_fun_devices_ajax"),
    path("add_devices",views.add_devices, name="add_devices"),
    path("get_devices_ajax",views.get_devices_ajax, name="get_devices_ajax"),
    path("edit_devices",views.edit_devices, name="edit_devices"),
    path("delete_devices",views.delete_devices, name="delete_devices"),
    path("add_emp_data",views.add_emp_data, name="add_emp_data"),
    path("get_EmployeesData_ajax",views.get_EmployeesData_ajax, name="get_EmployeesData_ajax"),
    path("edit_EmployeesData",views.edit_EmployeesData, name="edit_EmployeesData"),
    path("get_view_fun_EmployeesData_ajax",views.get_view_fun_EmployeesData_ajax, name="get_view_fun_EmployeesData_ajax"),
]

